services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: klontong
    volumes:
      - data:/data/postgres
    ports:
      - 5432:5432
    restart: always
    network_mode: 'host'

  app:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    network_mode: 'host'

volumes:
  data: